; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[common]
build_unflags =
	-std=gnu++11
build_flags =
	-std=gnu++14
lib_deps =
extra_scripts =
monitor_speed = 115200

[env:native]
platform = native
build_unflags =
    ${common.build_unflags}
build_flags =
    ${common.build_flags}
    -DPLATFORM_NATIVE
    -DMICROSTORE_USE_POSIXFS
    ;-DMICROSTORE_USE_STDIOFS
lib_deps =
	${common.lib_deps}
lib_compat_mode = off

[env:native_debug]
platform = native
build_unflags =
	${common.build_unflags}
build_flags =
	${common.build_flags}
	; CBA TEST
	;-fsanitize=address
	-fno-omit-frame-pointer
	-g
	;-O1
	-O0
    -DPLATFORM_NATIVE
    -DMICROSTORE_USE_POSIXFS
    ;-DMICROSTORE_USE_STDIOFS
lib_deps =
	${common.lib_deps}
lib_compat_mode = off

[env:heltec_wifi_lora_32_V3]
framework = arduino
platform = espressif32
; Use the pioarduino fork for Arduino Core 3.x / ESP-IDF 5.x support
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
; Very stable
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
; Latest stable
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
board = heltec_wifi_lora_32_V3
;board_build.partitions = partitions_esp32.csv
board_build.partitions = no_ota.csv
board_upload.flash_size = 8MB
board_build.filesystem = littlefs
build_unflags =
    ${common.build_unflags}
build_flags =
    ${common.build_flags}
    -DPLATFORM_ESP32
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DMICROSTORE_USE_LITTLEFS
    ;-DMICROSTORE_USE_SPIFFS
lib_deps =
    ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
monitor_filters = esp32_exception_decoder

[env:wiscore_rak4631]
framework = arduino
platform = nordicnrf52
;board = wiscore_rak4631
board = rak4630
board_build.variants_dir = variants
board_build.variant = rak4630
board_build.partitions = no_ota.csv
build_unflags =
    ${common.build_unflags}
build_flags =
    ${common.build_flags}
    -DPLATFORM_NRF52
    -DMICROSTORE_USE_INTERNALFS
    ;-DMICROSTORE_USE_FLASHFS
lib_deps =
    ${common.lib_deps}
	Adafruit_SPIFlash=symlink://../Adafruit_SPIFlash
extra_scripts = ${common.extra_scripts}
